import img from "./Images/Travelholic.PNG"
import img1 from "./Images/multiverse1.PNG"
import img6 from "./Images/pizzashop.PNG"
import img8 from "./Images/delivery.PNG"
import img9 from "./Images/newsgrid.PNG"
import img10 from "./Images/trophy.PNG"
import img12 from "./Images/travelholicfyp.PNG"
import img14 from "./Images/chatapp.png"

const DataApi = [ 
  {
    id: 1,
    image: img,
    demo: "https://chimerical-rolypoly-91c3f4.netlify.app/",
    livelink: "https://chimerical-rolypoly-91c3f4.netlify.app/",
    github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
    title: "Travel Site - Frontend",
    desc: "Made for a Travel & tourism company that provides a platform to not only Travel agents but also the targetted their clients. Fully adjusted for all types of screens",
    tech1: "SCSS",
    tech2: "REACTJS",
    tech3: "HOOKS",
  },
  {
    id: 2,
    image: img1,
    demo: "https://github.com/ShahzaibAftab/multiverse-ecom-fullstack",
    livelink: "https://github.com/ShahzaibAftab/multiverse-ecom-fullstack",
    github: "https://github.com/ShahzaibAftab/multiverse-ecom-fullstack",
    title: "Multiverse Ecom",
    desc: "My role involved architecting and implementing the backend infrastructure using Express.js, integrating Cloudinary for file handling, and implementing JWT for enhanced authentication and security Protocols. On the frontend, my focus was on API integration, data retrieval, and mutation operations using React Query, alongside managing state using Redux Toolkit. ",
    tech1: "MERN",
    tech2: "Authorization",
    tech3: "Optimization",
  },
  // {
  //   id: 7,
  //   image: img11,
  //   demo: "https://64f6fb34a5bd427adc989174--serene-banoffee-97d479.netlify.app/",
  //   livelink: "https://64f6fb34a5bd427adc989174--serene-banoffee-97d479.netlify.app/",
  //   github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
  //   title: "Safex",
  //   desc: "Sport site that keep records of all primary Games score, Upcoming Matches and track of all previous events and games",
  //   tech1: "PYTHON",
  //   tech2: "DJANGO",
  //   tech3: "VUE JS",
  // },
  {
    id: 8,
    image: img12,
    demo: "https://64f6f38b2525ca7a1a9820fa--fabulous-blini-c602e3.netlify.app/",
    livelink: "https://64f6f38b2525ca7a1a9820fa--fabulous-blini-c602e3.netlify.app/",
    github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
    title: "Travelholic - Multivendor Site",
    desc: "A multivendor Platform for travel and tourism companies to provide their Services, based on seperate panels for Admin, Vendor And Client. Authentication and customized Trips are Key features, Based upon Bidding Algorithm ",
    tech1: "REACT JS",
    tech2: "NODE JS",
    tech3: "MONGO DB",
  },
  {
    id: 2,
    image: img6,
    demo: "https://655345a77a48eb413a7bb190--lovely-cucurucho-e3a95e.netlify.app/",
    livelink: "https://655345a77a48eb413a7bb190--lovely-cucurucho-e3a95e.netlify.app/",
    github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
    title: "Pizza Shop",
    desc: "Developed responsive PSD to HTML webpage for a fast-food company, ensuring seamless adaptability across various screen sizes, including Mobile Phones, Tablets, and Desktops.",
    tech1: "HTML",
    tech2: "CSS",
    tech3: "JAVASCRIPT",
  },
  // {
  //   id: 15,
  //   image: img15,
  //   demo: "https://651d381ff8d4072f0bdf6664--zippy-cactus-e76da3.netlify.app/",
  //   livelink: "https://651d381ff8d4072f0bdf6664--zippy-cactus-e76da3.netlify.app/",
  //   github: "https://github.com/ShahzaibAftab/todolist-intermediate",
  //   title: "Todolist",
  //   desc: "Developed using States only. Contain features like delete all, make notes, edit, Delete e.t.c",
  //   tech1: "REACT JS",
  //   tech2: "CHAKRA UI",
  //   tech3: "HOOKS",
  // },
  // {
  //   id: 3,
  //   image: img14,
  //   demo: "https://github.com/ShahzaibAftab/Realtime-Chat-app",
  //   livelink: "https://github.com/ShahzaibAftab/Realtime-Chat-app",
  //   github: "https://github.com/ShahzaibAftab/Realtime-Chat-app",
  //   title: "Realtime Chat-App",
  //   desc: "Realtime Lightweight public Chat-app, Start by Entering your Name",
  //   tech1: "CHAKRA UI",
  //   tech2: "SOCKET.IO",
  //   tech3: "NODE JS",
  // },
  // {
  //   id: 4,
  //   image: img7,
  //   demo: "https://darling-cocada-927549.netlify.app/",
  //   livelink: "https://darling-cocada-927549.netlify.app/",
  //   github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
  //   title: "Photography Collection",
  //   desc: "Developed for Photography enthusiast Client for collection of his Memories",
  //   tech1: "HTML",
  //   tech2: "CSS",
  //   tech3: "JAVASCRIPT",
  // },
  {
    id: 5,
    image: img8,
    demo: "https://64e8a8bbdfe84c14cd08816b--subtle-frangipane-5a0e60.netlify.app/",
    livelink: "https://64e8a8bbdfe84c14cd08816b--subtle-frangipane-5a0e60.netlify.app/",
    github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
    title: "Delivery Site",
    desc: "Developed for Logistic company, fully Responsive, optimized for Mobile Phones, Tablets and Desktop.",
    tech1: "HTML",
    tech2: "CSS",
    tech3: "JAVASCRIPT, Dark Mode",
  },
  {
    id: 6,
    image: img9,
    demo: "https://64eef22824497451dacf0bb0--spiffy-dodol-2a710f.netlify.app/",
    livelink: "https://64eef22824497451dacf0bb0--spiffy-dodol-2a710f.netlify.app/",
    github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
    title: "NewsGrid",
    desc: "News Grid aimed at delivering a comprehensive and up-to-date news platform covering a wide spectrum of topics",
    tech1: "HTML",
    tech2: "CSS",
    tech3: "JAVASCRIPT",
  },
  {
    id: 7,
    image: img10,
    demo: "https://inspiring-maamoul-457e7b.netlify.app/",
    livelink: "https://inspiring-maamoul-457e7b.netlify.app/",
    github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
    title: "Sports Site",
    desc: "Sport site that keep records of all primary Games score, Upcoming Matches and track of all previous events and games",
    tech1: "HTML",
    tech2: "CSS",
    tech3: "JAVASCRIPT",
  },

  // {
  //   id: 8,
  //   image: img13,
  //   demo: "https://64f6fc363e38137e1511842f--unique-croissant-7c9658.netlify.app/",
  //   livelink: "https://64f6fc363e38137e1511842f--unique-croissant-7c9658.netlify.app/",
  //   github: "https://github.com/ShahzaibAftab/TravelholicLandingPage",
  //   title: "Trusted Auction System",
  //   desc: "Trusted Auction System is a web application developed using Django, a Python web framework. The system allows users to participate in online auctions, where they can upload products for bidding, place bids on products, and close auctions based on their preferred time.",
  //   tech1: "PYTHON",
  //   tech2: "DJANGO",
  //   tech3: "SQLITE",
  // },

  // {
  //   id: 5,
  //   image: img5,
  //   demo: "https://lucent-dango-ab0609.netlify.app/",
  //   livelink: "https://lucent-dango-ab0609.netlify.app/",
  //   github: "https://github.com/ShahzaibAftab/myweatherapp",
  //   title: "Weather App",
  //   desc: "Enter Your city and get weather updates. Data is Fetched and used using REST API. Icons are used. Screen is adjusted according to wider screens ",
  //   tech1: "ReactJS",
  //   tech2: "SASS",
  //   tech3: "REST API",
  // },

    // {
    //   id: 4,
    //   image: img4,
    //   demo: "https://celebrated-hummingbird-dc0478.netlify.app/",
    //   livelink: "https://celebrated-hummingbird-dc0478.netlify.app/",
    //   github: "https://github.com/ShahzaibAftab/todolist",
    //   title: "TodoList",
    //   desc: "Developed using Reactjs, Scss. State management is implemented, local storage is used to avoid data loss after reload",
    //   tech1: "REACTJS",
    //   tech2: "SASS",
    //   tech3: "LocalStorage",
    // },
    // {
    //   id: 3,
    //   image: img3,
    //   demo: "https://silly-salmiakki-bc6471.netlify.app/",
    //   livelink: "https://silly-salmiakki-bc6471.netlify.app/",
    //   github: "https://github.com/ShahzaibAftab/ResponsiveNavbar",
    //   title: "Responsive Navbar",
    //   desc: "Responsive Nabar developed by Reactjs and SCSS. Webkit Tools are used for appealing Scroll look, React Hooks are implemented",
    //   tech1: "HTML",
    //   tech2: "SCSS",
    //   tech3: "REACTJS",
    // },

    // {
    //   id: 4,
    //   image: img,
    //   demo: "youtube.com",
    //   livelink: "google.com",
    //   github: "github.com",
    //   title: "Hotel Website-6",
    //   desc: "Justo eos ipsum invidunt sit magna dolores, nonumy sadipscing sit justo sed, dolor takimata nonumy eos et sit dolor. Elitr.",
    //   tech1: "HTML",
    //   tech2: "CSS",
    //   tech3: "Javascript",
    // },
];

export default DataApi;
